version: '3.8'
services:
  user-service:
    build: ./services/user-service
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      JWT_SECRET: "nOEhg3+P/q7VCz6K7PhXywTnrF0+G/IGpDeXbGtZuDQ="
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  message-service:
    build: ./services/message-service
    ports:
      - "5001:5001"
    restart: always
    environment:
      MONGO_URI: mongodb://message-db:27017/messagesdb
    depends_on:
      - message-db
      - user-service
    
  message-db:
    image: mongo:latest
    container_name: message-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  like-service:
    build: ./services/like-service
    ports:
      - "5002:5002"
    restart: always
    depends_on:
      - message-service

volumes:
  postgres_data:
  mongo-data: